#' compare_pangenomes
#'
#' Compares pangenomes using anova
#'
#' @param fitA a `panfit` object generated by the `panstripe` function
#' @param fitB a `panfit` object generated by the `panstripe` function
#'
#' @return a list containing a summary of the comparison and the resulting `glm` model object
#'
#' @examples
#'
#' simA <- simulate_pan(rate=1e-2, ngenomes = 100)
#' simB <- simulate_pan(rate=1e-4, ngenomes = 100)
#' fA <- panstripe(simA$pa, simA$tree, nboot=0)
#' fB <- panstripe(simB$pa, simB$tree, nboot=0)
#' comp <- compare_pangenomes(fA, fB)
#'
#' @export
compare_pangenomes <- function(fitA, fitB){
  
  # input checks
  if (class(fitA) != 'panfit') stop('fitA is not of class `panfit`!')
  validate_panfit(fitA)
  if (class(fitB) != 'panfit') stop('fitB is not of class `panfit`!')
  validate_panfit(fitB)
  
  #combine data
  dat <- purrr::imap_dfr(list(fitA, fitB), ~{
    tibble::add_column(.x$data, pangenome=LETTERS[[.y]], .before=1)
  })
  dat$istip <- 1*dat$istip
  
  # fit model
  model <- stats::as.formula("acc ~ core*istip + height + height:core + istip:pangenome + core:pangenome")
  
  m <- glmmTMB::glmmTMB(model, data = dat, family = glmmTMB::tweedie)
  
  s <- summary(m)$coefficients$cond %>% 
    tibble::as_tibble(rownames = 'term')
  s <- s[s$term %in% c('istip:pangenomeB', 'core:pangenomeB'), , drop=FALSE]
  s$term <- ifelse(s$term=='core:pangenomeB', 'core', 'tip')
  colnames(s) <- c('term','estimate','std.error','statistic','p.value')
  
  return(list(
    summary=s,
    model=m
  ))
  
}
