# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dwelling_times <- function(tree, Q_eigen, Q, fl) {
    .Call(`_panplotter_dwelling_times`, tree, Q_eigen, Q, fl)
}

fractional_likelihoods <- function(edges, states, prior, tp) {
    .Call(`_panplotter_fractional_likelihoods`, edges, states, prior, tp)
}

