# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

WMPR_ASR_CPP <- function(Ntips, Nnodes, Nedges, Nstates, tree_edge, edge_length, tip_states, transition_costs, branch_length_exponent, weight_posteriors_by_scenario_counts, verbose, verbose_prefix) {
    .Call(`_panstripe_WMPR_ASR_CPP`, Ntips, Nnodes, Nedges, Nstates, tree_edge, edge_length, tip_states, transition_costs, branch_length_exponent, weight_posteriors_by_scenario_counts, verbose, verbose_prefix)
}

dwelling_times <- function(tree, Q_eigen, Q, fl) {
    .Call(`_panstripe_dwelling_times`, tree, Q_eigen, Q, fl)
}

fractional_likelihoods <- function(edges, states, prior, tp) {
    .Call(`_panstripe_fractional_likelihoods`, edges, states, prior, tp)
}

